language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
addons:
  firefox: "49.0"
before_script:
 - mysql < app/database/cloud-aray.sql -u root
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install
 - "sh -e /etc/init.d/xvfb start"
 - "export DISPLAY=:99.0"
 - "wget http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar"
 - "java -jar selenium-server-standalone-3.0.1.jar > /dev/null &"
 - sleep 5
 - php -S 127.0.0.1:8090 app/.htrouter.php &
 - sleep 5
script: (cd tests; phpunit --configuration PHPunit.xml --debug)